prometheus-node-exporter:
  enabled: true
kube-state-metrics:
  enabled: false
alertmanager:
  enabled: false
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
      - job_name: node-exporter
        static_configs:
          - targets:
              - nabilah-prom-prometheus-node-exporter.nabilah-prom:9100
      - job_name: nginx
        static_configs:
          - targets:
              - ingress-nginx-controller.ingress-nginx:10254

server:
  persistentVolume:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - nabilah-prom.sctp-sandbox.com
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "nabilah-prom.sctp-sandbox.com"
